Implement interface end to end connection view
mattieserver/netbox-topology-views pull request #188
Opened 2022-11-23 03:58 UTC by tgrusendorf

PR to add back in and end to end connection view, similar to what was implemented before.

I'm simplified the approach, rather than tracing cables, to use the same queryset and fields as NetBox already uses for the 'Interface Connections' view (host:8000/dcim/interface-connections/)

Users may want to show different combinations of links when selecting end-to-end interface connections (e.g., show wireless links but not cables), so I've added separate selection options for cables and wireless links, similar to what has already been done with Circuit Terminations and Power Feeds.

![image](https://user-images.githubusercontent.com/73901582/203466303-ad606a07-2a8d-4940-bc66-aa55c0fbf8f7.png)

The current code assumes that there will be only one path destination of type 'interface' for each interface connection.  I believe this is a valid assumption as NetBox doesn't allow you to connect multiple cables to a single interface.

@mattieserver, I'd appreciate your comments.

2022-11-23 04:00 UTC, tgrusendorf commented
Closes issue #151.

2022-11-23 09:57 UTC, mattieserver commented
Hi,

It might be a good idea to rename to filter label to something like " show logical connections" as the previous implemention showed the full path of the cable. If I added the "cabling" role to the intermediary device roles it traced and added any extra device in the path that matches that role, so it added the full path for the connection.  Whereas this implemention is pure logical, skipping any intermidiate device.


Selecting both "show cables" and "show end-to-end interface connects" show 2 cables per actual connection. (Same with wireless links). This could be "confusing" for users.

2022-11-23 14:35 UTC, tgrusendorf commented
I agree - we could also name the filter label just "Show Interface Connections" to align with the existing NetBox view, but I think 'Show Logical Connections' is clearer.

Any suggestion to reduce the confusion if a user selects both "Show Cables" and "Show Logical Connections"?  Maybe we just add some instructions to the "Use" section in README.

2022-11-30 19:33 UTC, mattieserver commented
Yes, updating the readme + release notes will do i think.
I might add the option in the views.py if 'show_interfaces' is enabled the disable the 'show_cables' option. (or just return nothing since we currently have no way the send a error msg).

2022-12-02 02:44 UTC, tgrusendorf commented
Thanks for the commit, I've now updated the readme and would appreciate your comments.

2022-12-10 13:28 UTC, dreng commented
> Thanks for the commit, I've now updated the readme and would appreciate your comments.

I hope you appreciate my comment as well. :-)

Instead of writing in the README.md how not to use it, I would rather make sure that you can't use it wrong. Use a radio field or a choice field instead of two check boxes as the given choices should be mutually exclusive.

Btw., would you mind to update your fork and resolve the merge conflicts?

2022-12-11 19:46 UTC, tgrusendorf commented
Rebased to resolve merge conflicts. I'll play with a radio button for cables vs logical interfaces and see how it looks, but we'll need to include an option for 'neither' in case the user wants to only show other things (e.g., just power or wireless).  

This week in my dev system I actually used it with both cables and logical connections turned on while I was working on cables patched through multiple patch panels and wanted an overlay of the end-to-end connections, so I'm wondering if that's a rare but valid use case. Maybe having a different edge style for logical connections would help.

2022-12-16 11:57 UTC, dreng commented
@tgrusendorf 
I just set up a fresh VM with the current NetBox develop branch (v3.4.1-dev) and I fetched your pull request. I also imported the [NetBox demo data](https://github.com/netbox-community/netbox-demo-data). This is what I get when I just tick "Show Logical Connections" and leave everything else as it is:

> Internal Server Error: /plugins/netbox_topology_views/topology/
Traceback (most recent call last):
  File "/home/mario/src/.venvs/netbox/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/mario/src/.venvs/netbox/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mario/src/.venvs/netbox/lib/python3.9/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mario/src/.venvs/netbox/lib/python3.9/site-packages/django/contrib/auth/mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/mario/src/.venvs/netbox/lib/python3.9/site-packages/django/views/generic/base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/mario/src/netbox-topology-views/netbox_topology_views/views.py", line 629, in get
    topo_data = get_topology_data(
  File "/home/mario/src/netbox-topology-views/netbox_topology_views/views.py", line 429, in get_topology_data
    termination_b = { "termination_name": destination.name, "termination_device_name": destination.device.name, "device_id": destination.device.id }
AttributeError: 'Module' object has no attribute 'name'
Internal Server Error: /plugins/netbox_topology_views/topology/
Traceback (most recent call last):
  File "/home/mario/src/.venvs/netbox/lib/python3.9/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/mario/src/.venvs/netbox/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mario/src/.venvs/netbox/lib/python3.9/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/mario/src/.venvs/netbox/lib/python3.9/site-packages/django/contrib/auth/mixins.py", line 109, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/mario/src/.venvs/netbox/lib/python3.9/site-packages/django/views/generic/base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/mario/src/netbox-topology-views/netbox_topology_views/views.py", line 629, in get
    topo_data = get_topology_data(
  File "/home/mario/src/netbox-topology-views/netbox_topology_views/views.py", line 429, in get_topology_data
    termination_b = { "termination_name": destination.name, "termination_device_name": destination.device.name, "device_id": destination.device.id }
AttributeError: 'Module' object has no attribute 'name'

2022-12-16 16:00 UTC, tgrusendorf commented
Thanks @dreng.  I believe you've exposed two problems.  One is an error in my branch that I'll fix today, the other appears to be invalid connections in the 3.4 Netbox demo data.  In the demo data it is showing some interfaces connected directly to modules (e.g. dmi01-akrom-rtr01 GigabitEthernet0/0/0) when the cable shows it's connected to a circuit.  Cable traces on these connections cause an error as well.

![image](https://user-images.githubusercontent.com/73901582/208138577-14ad0271-5c70-4c87-b554-111922a2174d.png)

![image](https://user-images.githubusercontent.com/73901582/208138703-0baf8a6b-0ae1-4d19-b346-1cdd5656f732.png)

2022-12-20 17:47 UTC, dreng commented
@tgrusendorf Thank you for continuing to work on this. I have replaced the demo data in my environment with real data to avoid such supposed errors in the future.
I tinkered around with this PR today and I think it's just a few steps away from being ready to be merged. Some thoughts about two points we discussed before:

1. The arrows look great for it's purpose. I found it difficult to seperate cables from logical connections though. I defined a dotted line with arrows and found it very satisfying. Have a look at the screenshots below. What do you thing about it?
2. I think that cables and logical connections are redundant if "connection" and "link peer" are the same. While the first of the following two scenarios is okay and can be useful, the second one isn't. So I would suggest dropping the logical connections in this case.

![logicalconnok](https://user-images.githubusercontent.com/20901110/208730723-0e1dbce4-d6cd-4184-a20e-e1d6aa4dabc4.png)

![logicalconnbad png](https://user-images.githubusercontent.com/20901110/208730750-8156031c-5351-495c-8007-bc3d7ba5542e.png)

2022-12-20 17:51 UTC, dreng commented on netbox_topology_views/views.py
> +        edge["width"] = 3
```suggestion
        edge["width"] = 3
        edge["dashes"] = [1, 10, 1, 10]
```

2022-12-27 12:30 UTC, dreng commented
Looks pretty complete now. Although it is a good idea to let the user decide if he want's to see redundant cables and logical connections, I'm not sure if this should be a default setting in the __init__.py rather than a checkbox like all the other options. But this should be addressed in a new issue in my opinion since it is a general question if we move all of the checkboxes to __init_.py. In my opinion all of this settings should belong to a saved filter and should be consolidated into one drop-down.

@mattieserver I think this is ready to be merged. What do you think?

2022-12-27 13:07 UTC, dreng requested changes

2022-12-27 13:07 UTC, dreng commented on README.md
> +| hide_single_cable_logical_conns      | False                                                                                                                                          | (bool) Set to
```suggestion
| hide_single_cable_logical_conns      | False                                                                                                                                          | (bool) Set to True if you want to hide duplicate cables & logical connections |
```

2022-12-27 13:16 UTC, mattieserver commented
I think we can merge this.
If we move the options/filters it should be in a new PR.

If we get feedback regarding the duplicate cables/logical connections we can also look to add a message with the toast.js that was added in another PR.

2022-12-27 13:49 UTC, merged

2022-12-27 17:22 UTC, tgrusendorf commented
Thanks - wasn't expecting to wake up today to find this already merged.

I put the redundant connection / cable option in init.py because I didn't think it really belonged on the 'Filters' tab as it's more of a visualization option (I guess the same could be said of 'Save Coordinates' too).  In the future maybe an additional tab is warranted for display options.

I added the option to change the dash style for interface connections because I'm not really loving the dashed style TBH, but that's just personal preference.  I suppose that's something else that could go on a display options tab in the future.

Thanks for the feedback and testing throughout this PR.